import type { AccionClave, ContextoDeAccion, NivelDeAccion } from "../../src/core/permisos/acciones";
import type { ModuloId } from "../../src/core/modulos/catalogo";

/**
 * La matriz de fábrica ESPERADA de las acciones, escrita a mano y a propósito aparte del catálogo (`src/core/permisos/acciones.ts`): si
 * alguien cambia el contexto, el nivel mínimo o quién edita una acción en el catálogo, este archivo no cambia solo y
 * `matriz-de-fabrica.test.ts` falla — el cambio queda a la vista en el diff y hay que hacerlo dos veces, adrede. Es la forma barata de
 * que un permiso no se abra por descuido (por ejemplo, darle una acción de administrador a un rol de operario).
 */
export interface FilaEsperada {
  modulo: ModuloId;
  contexto: ContextoDeAccion;
  nivelMinimo: NivelDeAccion;
  /** Roles que EDITAN la acción desde el arranque (seed). */
  roles: readonly ("admin" | "operador")[];
}

export const MATRIZ_ESPERADA: Readonly<Record<AccionClave, FilaEsperada>> = {
  alta_producto: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_editar: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_asignar_insumo: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_sincronizar_precio_carta: { modulo: "carta", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  guardar_receta: { modulo: "recetas", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  grupos_familia: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  secciones: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  unidades: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  proveedores: { modulo: "proveedores_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  categorias: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  margen_objetivo_editar: { modulo: "recetas", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  motivos_merma: { modulo: "stock", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  motivos_destino_consumo: { modulo: "stock", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_ver: { modulo: "carta", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_secciones: { modulo: "carta", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_generos: { modulo: "carta", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_contenido_producto: { modulo: "carta", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_producto_descuento: { modulo: "carta", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_items_agrupados: { modulo: "carta", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_portal: { modulo: "carta", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_promo_definir: { modulo: "promociones", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_promo_activar: { modulo: "promociones", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_promo_precio_local: { modulo: "promociones", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_tema: { modulo: "carta", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  stock_minimo: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  ver_stock: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  precio_local: { modulo: "catalogo_basico", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  comparar_precios: { modulo: "compras", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  notificar_alertas: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  insumos_mezclados: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  gestion_usuarios: { modulo: "administracion", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  gestion_permisos: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  gestion_roles: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  activar_usuario_sucursal: { modulo: "administracion", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  notas_usuario_sucursal: { modulo: "administracion", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  apagar_cuenta_empresa: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  proceso_compra: { modulo: "compras", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_produccion: { modulo: "produccion", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_consumo: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_ajuste: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  proceso_control: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_transferencia: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_merma: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_venta: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_consignacion: { modulo: "consignacion", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_cliente: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_proveedor: { modulo: "compras", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_ver_bandeja: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_solicitar: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_enviar_directo: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_aprobar: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_cancelar_solicitud: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_rechazar_solicitud: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_aceptar: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_rechazar_envio: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_confirmar_reingreso: { modulo: "traspasos", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  cancelar_conteo: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  anular_venta: { modulo: "salon", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  anular_compra: { modulo: "compras", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  corregir_compra: { modulo: "compras", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  capacidades_sucursal: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  alta_sucursal: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  activar_sucursal: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  renombrar_sucursal: { modulo: "administracion", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pagar_consignante: { modulo: "consignacion", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  ver_auditoria: { modulo: "administracion", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  ver_auditoria_empresa: { modulo: "administracion", contexto: "empresa", nivelMinimo: "gerente", roles: [] },
  traspasar_gerencia: { modulo: "administracion", contexto: "empresa", nivelMinimo: "gerente", roles: [] },
  reporte_resumen: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_consolidado: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_periodo: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_categorias: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_ventas_por_seccion: { modulo: "salon", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_costos: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_compras: { modulo: "compras", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_rendimiento_recetas: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_rendimiento_sucursal: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_valuacion: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_boletas: { modulo: "salon", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_descuentos_clientes: { modulo: "salon", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_descuentos_productos: { modulo: "salon", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_margen_promociones: { modulo: "promociones", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_historial_importes: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_perdidas: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_devoluciones: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_diferencias: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_vencimientos: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_salud: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_historial: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_trazabilidad: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_rotacion_mesas: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_sin_receta: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_insumos_sin_receta: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_conteos: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  reporte_huecos_catalogo: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pos_mesas: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_tomar_pedido: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_anular_item: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_cerrar_cuenta: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  calibrar_rendimiento_local: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  receta_sucursal_editar: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  receta_sucursal_copiar: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  receta_sucursal_volver_central: { modulo: "recetas", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_copiar_de_sucursal: { modulo: "carta", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  clientes: { modulo: "clientes_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pos_asignar_cliente: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  stock_seccion_habitual: { modulo: "stock", contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  pos_emitir_boleta_corregida: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  insumo_renombrar_fusionar: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  conteo_resolver_pendiente: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  stock_reclasificar: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  conteo_frecuencia: { modulo: "stock", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_ver_catalogo: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_presentaciones: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  insumo_alta: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  categoria_alta: { modulo: "catalogo_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proveedor_alta: { modulo: "proveedores_basico", contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_disponibilidad: { modulo: "catalogo_basico", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  pos_alta_mesa: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_limite_mesas_abiertas: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_abrir_cuenta: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_enviar_a_cocina: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_liberar_mesa: { modulo: "salon", contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
};
