import type { AccionClave, ContextoDeAccion, NivelDeAccion } from "../../src/core/permisos/acciones";

/**
 * La matriz de fábrica ESPERADA de las acciones, escrita a mano y a propósito aparte del catálogo (`src/core/permisos/acciones.ts`): si
 * alguien cambia el contexto, el nivel mínimo o quién edita una acción en el catálogo, este archivo no cambia solo y
 * `matriz-de-fabrica.test.ts` falla — el cambio queda a la vista en el diff y hay que hacerlo dos veces, adrede. Es la forma barata de
 * que un permiso no se abra por descuido (por ejemplo, darle una acción de administrador a un rol de operario).
 */
export interface FilaEsperada {
  contexto: ContextoDeAccion;
  nivelMinimo: NivelDeAccion;
  /** Roles que EDITAN la acción desde el arranque (seed). */
  roles: readonly ("admin" | "operador")[];
}

export const MATRIZ_ESPERADA: Readonly<Record<AccionClave, FilaEsperada>> = {
  alta_producto: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  editar_producto: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  guardar_receta: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  grupos_familia: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  secciones: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  unidades: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  proveedores: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  categorias: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
motivos_merma: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  motivos_destino_consumo: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_ver: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_secciones: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_generos: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_contenido_producto: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_items_agrupados: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_portal: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  carta_promos: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  carta_tema: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  stock_minimo: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  ver_stock: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  precio_local: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  promociones_config: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  comparar_precios: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  notificar_alertas: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  insumos_mezclados: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  sincronizar_proveedores: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  ejecutar_tests: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  gestion_usuarios: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  gestion_permisos: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  proceso_compra: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_produccion: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_consumo: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_ajuste: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  proceso_control: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_transferencia: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_merma: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_venta: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_consignacion: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_cliente: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proceso_devolucion_proveedor: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_ver_bandeja: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_solicitar: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_enviar_directo: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_aprobar: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_cancelar_solicitud: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_rechazar_solicitud: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_aceptar: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_rechazar_envio: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  traspaso_confirmar_reingreso: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  cancelar_conteo: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  anular_venta: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  anular_compra: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  corregir_compra: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  capacidades_sucursal: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  alta_sucursal: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pagar_consignante: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  ver_auditoria: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_resumen: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_consolidado: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_periodo: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_categorias: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_ventas_por_seccion: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_costos: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_compras: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_rendimiento_recetas: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_rendimiento_sucursal: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_valuacion: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_boletas: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_descuentos_clientes: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_margen_promociones: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_historial_importes: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_perdidas: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_devoluciones: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_diferencias: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_vencimientos: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_salud: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_historial: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_trazabilidad: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_rotacion_mesas: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  reporte_sin_receta: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_insumos_sin_receta: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  reporte_conteos: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  reporte_huecos_catalogo: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pos_mesas: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_tomar_pedido: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_anular_item: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_cerrar_cuenta: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  calibrar_rendimiento_local: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  clientes: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  pos_asignar_cliente: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  stock_seccion_habitual: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  pos_emitir_boleta_corregida: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  insumo_renombrar_fusionar: { contexto: "empresa", nivelMinimo: "administrador", roles: ["admin"] },
  conteo_resolver_pendiente: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  stock_reclasificar: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  conteo_frecuencia: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  promociones_activar: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  promociones_marcar_combo: { contexto: "sucursal", nivelMinimo: "administrador", roles: ["admin"] },
  producto_ver_catalogo: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_presentaciones: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  insumo_alta: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  categoria_alta: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  proveedor_alta: { contexto: "empresa", nivelMinimo: "operario", roles: ["admin", "operador"] },
  producto_disponibilidad: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin", "operador"] },
  pos_alta_mesa: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_limite_mesas_abiertas: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_abrir_cuenta: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_enviar_a_cocina: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
  pos_liberar_mesa: { contexto: "sucursal", nivelMinimo: "operario", roles: ["admin"] },
};
