/**
 * Fachada PÚBLICA y PURA del dominio `reportes` (Task #41, Fase C3).
 *
 * Fuera de `core/reportes/` se importa esta fachada o `public-servidor.ts`, nunca un archivo interno (regla
 * `sin-internals-de-otro-dominio` de `.dependency-cruiser.cjs`). Acá van SOLO los módulos que no alcanzan `@/lib/db` ni el
 * runtime de Prisma, ni directa ni transitivamente (regla `publico-puro`). Lo que sí toca la base va en
 * `public-servidor.ts`.
 *
 * Solo TIPOS (se borran al compilar): la función `compararRendimientosPorSucursal` hace consultas y va en `public-servidor.ts` (Pureza Fase 2, paso 2.2).
 *
 * Solo reexports explícitos (nunca `export *`, nunca lógica), y solo lo que hoy se usa desde afuera del dominio.
 */
export type { FiltroComparacionRendimiento, FilaComparacionRendimiento } from "./rendimiento-por-sucursal";
export { FOOD_COST_OBJETIVO_PCT } from "./margen-objetivo";
export { resolverObjetivoFoodCost } from "./margen-objetivo";
export { resolverRangoDeReporte } from "./rango-por-defecto";
export type { FilaDebidoConsignante } from "./consignacion";
export type { FilaStockSinVenderConsignacion } from "./consignacion";
export type { FilaResumenConsolidado } from "./resumen-consolidado";
export type { FilaCostoProducto } from "./costos";
export type { FilaImpactoInsumo } from "./costos";
export { resolverAccionFaltante } from "./accion-faltante";
export type { FilaDescuentoCliente } from "./descuentos-clientes";
export type { FilaDescuentoProducto } from "./descuentos-productos";
export { diasAtrasDeUrl } from "./dias-atras";
export type { FilaDevolucionProducto } from "./devoluciones";
export type { FilaDiferenciaAjuste } from "./diferencias-ajustes";
export type { IngredienteRecetaVigente } from "./historial-producto";
export type { FilaCompraHistorial } from "./historial-vistas";
export type { ResumenCompras } from "./historial-vistas";
export type { FilaVentaPorDia } from "./historial-vistas";
export type { EventoHistorialProducto } from "./historial-producto";
export type { QueMostrar } from "./historial-vistas";
export type { RangoHistorial } from "./historial-vistas";
export { agruparVentasPorDia } from "./historial-vistas";
export { filtrarEventosKardex } from "./historial-vistas";
export { quitarDineroDeEventos } from "./historial-vistas";
export { resolverRangoHistorial } from "./historial-vistas";
export { resumirCompras } from "./historial-vistas";
export type { FilaInsumoSinReceta } from "./insumos-sin-receta";
export type { FilaMargenPromocion } from "./margen-promociones";
export type { FilaPerdida } from "./perdidas";
export type { ComparativaPreciosDelPeriodo } from "./periodo";
export type { FilaAlertaDigest } from "./periodo";
export type { FilaGastoPorGrupo } from "./periodo";
export { SIN_PROVEEDOR } from "./compras-filtros";
export type { FilaMargenProducto } from "./periodo";
export type { FilaCompraPorProveedor } from "./periodo";
export type { FilaGastoPorInsumo } from "./periodo";
export type { FilaPrecioInsumo } from "./periodo";
export type { FilaImpactoRecetaPorPeriodo } from "./costos";
export { ETIQUETA_ROTULO } from "./rendimiento-recetas-vistas";
export { desvioEsNotable } from "./rendimiento-recetas-vistas";
export type { RotuloLinea } from "./rendimiento-recetas-vistas";
export type { MetodoRendimiento } from "./rendimiento-conciliado";
export { explicarConfianza } from "./rendimiento-recetas-vistas";
export type { Confianza } from "./rendimiento-recetas-vistas";
export { armarSaludPorProducto } from "./salud-por-producto";
export type { FilaSaludProducto } from "./salud-por-producto";
export type { FilaVentaSinReceta } from "./ventas-sin-receta";
export type { OperacionEncontrada } from "./trazabilidad";
export type { ItemOperacion } from "./trazabilidad";
export type { FilaValuacionInventario } from "./valuacion";
export { resolverRangoPorDefecto } from "./rango-por-defecto";
export type { UltimaCotizacion } from "./cotizacion-dolar";
export type { OpcionRango } from "./rango-por-defecto";
export { redondearCantidad } from "./redondeo";
export { TAMANO_PAGINA_COMPRAS } from "./compras-registradas";
export type { FiltroCompras } from "./compras-registradas";
export type { RenglonCompra } from "./compras-registradas";
export type { CompraRegistrada } from "./compras-registradas";
export type { PaginaCompras } from "./compras-registradas";
export type { ReporteConsignacion } from "./consignacion";
export type { IndiceRecetas } from "./comun";
export type { InfoProductoReporte } from "./comun";
export { diaUtc } from "./costo-historico";
export { costosDeInsumosPorDia } from "./costo-historico";
export { claveCostoHistorico } from "./costo-historico";
export type { ItemParaMargenReal } from "./margen-real";
export type { ReporteDescuentosClientes } from "./descuentos-clientes";
export type { ReporteDescuentosProductos } from "./descuentos-productos";
export { resolverAccionSinCostoReposicion } from "./accion-faltante";
export type { AccProducto } from "./devoluciones";
export type { ReporteDevoluciones } from "./devoluciones";
export type { EstadoDiferencia } from "./diferencias-ajustes";
export type { RecetaQueUsaInsumo } from "./diferencias-ajustes";
export type { FilaMovimientoHistorial } from "./historial-producto";
export type { FilaBusquedaProducto } from "./historial-producto";
export type { HistorialProducto } from "./historial-producto";
export type { ProblemaUnidadMezclada } from "./huecos-catalogo";
export type { ReporteHuecosCatalogo } from "./huecos-catalogo";
export type { ObjetivosDeMargen } from "./margen-objetivo";
export type { AcumuladoPromo } from "./margen-promociones";
export type { ReporteMargenPromociones } from "./margen-promociones";
export type { FilaMargenRealProducto } from "./margen-real";
export type { MargenRealDelPeriodo } from "./margen-real";
export type { ReportePerdidas } from "./perdidas";
export type { ItemPeriodo } from "./periodo-tipos";
export type { VentasDelPeriodo } from "./periodo-ventas";
export type { MargenDelPeriodo } from "./periodo-margen";
export type { FilaVentaProducto } from "./periodo-ventas";
export type { RatioGastoVentas } from "./periodo-ratio";
export { hayObjetivosCargados } from "./margen-objetivo";
export { resumirFueraDeObjetivo } from "./margen-objetivo";
export { rangoUtc } from "./periodo-tipos";
export type { FiltrosPeriodo } from "./periodo-tipos";
export { generarDigestAlertas } from "./periodo-alertas";
export { calcularComprasDelPeriodo } from "./periodo-compras";
export { calcularGastoPorInsumoDelPeriodo } from "./periodo-compras";
export { calcularVentasDelPeriodo } from "./periodo-ventas";
export { agruparVentasPorCategoria } from "./periodo-categorias";
export { pvSinCategoriaDe } from "./periodo-categorias";
export { calcularCantidadTeoricaBruta } from "./rendimiento-recetas-vistas";
export { calcularDesviacionPorcentaje } from "./rendimiento-recetas-vistas";
export type { ValorPorSucursal } from "./rendimiento-por-sucursal";
export type { CostoMP } from "./comun";
export { bandaDeRuidoDeLote } from "./rendimiento-recetas-vistas";
export { calcularCantidadEstimadaNeta } from "./rendimiento-recetas-vistas";
export { compararPorImpacto } from "./rendimiento-recetas-vistas";
export { impactoDelDesvio } from "./rendimiento-recetas-vistas";
export { motivoSinEstimacion } from "./rendimiento-recetas-vistas";
export { motivoSinEstimacionConteo } from "./rendimiento-recetas-vistas";
export { rotularLineaDeReceta } from "./rendimiento-recetas-vistas";
export { anclasValidasEnVentana } from "./rendimiento-conciliado";
export { clavePar } from "./rendimiento-conciliado";
export { consumoRealDelTramo } from "./rendimiento-conciliado";
export { elegirAnclas } from "./rendimiento-conciliado";
export { finDelDiaUtc } from "./rendimiento-conciliado";
export { limitesDelTramo } from "./rendimiento-conciliado";
export type { Anclas } from "./rendimiento-conciliado";
export type { CandidatoAncla } from "./rendimiento-conciliado";
export type { MovimientoParaConciliar } from "./rendimiento-conciliado";
export type { UsoDeInsumo } from "./rendimiento-recetas";
export type { Pool } from "./rendimiento-recetas";
export type { ResultadoPoolCompartido } from "./rendimiento-recetas";
export type { FilaRendimientoSimple } from "./rendimiento-recetas";
export type { FilaRendimientoCompartido } from "./rendimiento-recetas";
export type { ResumenFinanciero } from "./resumen-operativo";
export type { ResumenOperativo } from "./resumen-operativo";
export type { ReporteRotacionMesas } from "./rotacion-mesas";
export { calcularRotacionMesas } from "./rotacion-mesas";
export { TAMANO_PAGINA_TICKETS } from "./tickets-emitidos";
export type { FiltroTickets } from "./tickets-emitidos";
export type { LineaTicketEmitido } from "./tickets-emitidos";
export type { FilaTicketEmitido } from "./tickets-emitidos";
export type { PaginaTickets } from "./tickets-emitidos";
export type { DatosOperacion } from "./trazabilidad";
export type { ReporteValuacionInventario } from "./valuacion";
export type { FilaLoteProximoAVencer } from "./vencimientos";
export type { FilaConciliacionVencimiento } from "./vencimientos";
export { armarIndiceRecetas, armarMapaProductos, asegurarIndiceRecetasDeLaSucursal } from "./comun";
export { calcularCostosYMargenesDesde, calcularImpactoInsumosDesde, calcularImpactoRecetasPorPeriodoDesde, resolverCostoRecetaCompleta } from "./costos";
