-- Reversa de la migración multiempresa_estructura (ADR-007, A2). Escrita a mano sobre el diff inverso de Prisma.
-- Solo es válida mientras la base tenga UNA empresa: recrea las unicidades globales (nombre, código, slug) y las FK simples.
-- Con datos de dos empresas esas unicidades fallarían: primero hay que unificar o borrar la empresa sobrante.
-- Aplicar como el dueño de las tablas:  psql "$DIRECT_URL" -v ON_ERROR_STOP=1 -1 -f down.sql
-- (Prisma no ejecuta este archivo; `_prisma_migrations` hay que ajustarla a mano con `prisma migrate resolve --rolled-back`.)

-- 1) Se sueltan FK e índices nuevos.
ALTER TABLE "Sucursal" DROP CONSTRAINT "Sucursal_empresaId_fkey";
ALTER TABLE "Rol" DROP CONSTRAINT "Rol_empresaId_fkey";
ALTER TABLE "UsuarioSucursal" DROP CONSTRAINT "UsuarioSucursal_empresaId_fkey";
ALTER TABLE "UsuarioSucursal" DROP CONSTRAINT "UsuarioSucursal_empresaId_sucursalId_fkey";
ALTER TABLE "UsuarioSucursal" DROP CONSTRAINT "UsuarioSucursal_empresaId_rolId_fkey";
ALTER TABLE "PermisoRol" DROP CONSTRAINT "PermisoRol_empresaId_fkey";
ALTER TABLE "PermisoRol" DROP CONSTRAINT "PermisoRol_empresaId_rolId_fkey";
ALTER TABLE "CapacidadSucursal" DROP CONSTRAINT "CapacidadSucursal_empresaId_fkey";
ALTER TABLE "CapacidadSucursal" DROP CONSTRAINT "CapacidadSucursal_empresaId_sucursalId_fkey";
ALTER TABLE "RegistroAuditoria" DROP CONSTRAINT "RegistroAuditoria_empresaId_fkey";
ALTER TABLE "RegistroAuditoria" DROP CONSTRAINT "RegistroAuditoria_empresaId_sucursalId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_categoriaId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_unidadCompraId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_unidadStockId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_insumoId_fkey";
ALTER TABLE "Producto" DROP CONSTRAINT "Producto_empresaId_proveedorConsignacionId_fkey";
ALTER TABLE "DisponibilidadProducto" DROP CONSTRAINT "DisponibilidadProducto_empresaId_fkey";
ALTER TABLE "DisponibilidadProducto" DROP CONSTRAINT "DisponibilidadProducto_empresaId_sucursalId_fkey";
ALTER TABLE "DisponibilidadProducto" DROP CONSTRAINT "DisponibilidadProducto_empresaId_productoId_fkey";
ALTER TABLE "Insumo" DROP CONSTRAINT "Insumo_empresaId_fkey";
ALTER TABLE "Insumo" DROP CONSTRAINT "Insumo_empresaId_grupoId_fkey";
ALTER TABLE "Grupo" DROP CONSTRAINT "Grupo_empresaId_fkey";
ALTER TABLE "Grupo" DROP CONSTRAINT "Grupo_empresaId_grupoPadreId_fkey";
ALTER TABLE "CategoriaProducto" DROP CONSTRAINT "CategoriaProducto_empresaId_fkey";
ALTER TABLE "Unidad" DROP CONSTRAINT "Unidad_empresaId_fkey";
ALTER TABLE "Presentacion" DROP CONSTRAINT "Presentacion_empresaId_fkey";
ALTER TABLE "Presentacion" DROP CONSTRAINT "Presentacion_empresaId_productoId_fkey";
ALTER TABLE "Presentacion" DROP CONSTRAINT "Presentacion_empresaId_unidadCompraId_fkey";
ALTER TABLE "Proveedor" DROP CONSTRAINT "Proveedor_empresaId_fkey";
ALTER TABLE "PagoConsignante" DROP CONSTRAINT "PagoConsignante_empresaId_fkey";
ALTER TABLE "PagoConsignante" DROP CONSTRAINT "PagoConsignante_empresaId_sucursalId_fkey";
ALTER TABLE "PagoConsignante" DROP CONSTRAINT "PagoConsignante_empresaId_proveedorId_fkey";
ALTER TABLE "ProveedorPorProducto" DROP CONSTRAINT "ProveedorPorProducto_empresaId_fkey";
ALTER TABLE "ProveedorPorProducto" DROP CONSTRAINT "ProveedorPorProducto_empresaId_productoId_fkey";
ALTER TABLE "ProveedorPorProducto" DROP CONSTRAINT "ProveedorPorProducto_empresaId_proveedorId_fkey";
ALTER TABLE "ProveedorPorProducto" DROP CONSTRAINT "ProveedorPorProducto_empresaId_unidadCompraId_fkey";
ALTER TABLE "Cliente" DROP CONSTRAINT "Cliente_empresaId_fkey";
ALTER TABLE "RecetaVersion" DROP CONSTRAINT "RecetaVersion_empresaId_fkey";
ALTER TABLE "RecetaVersion" DROP CONSTRAINT "RecetaVersion_empresaId_productoId_fkey";
ALTER TABLE "RecetaVersion" DROP CONSTRAINT "RecetaVersion_empresaId_rendimientoUnidadId_fkey";
ALTER TABLE "RecetaVersion" DROP CONSTRAINT "RecetaVersion_empresaId_racionUnidadId_fkey";
ALTER TABLE "RecetaIngrediente" DROP CONSTRAINT "RecetaIngrediente_empresaId_fkey";
ALTER TABLE "RecetaIngrediente" DROP CONSTRAINT "RecetaIngrediente_empresaId_recetaVersionId_fkey";
ALTER TABLE "RecetaIngrediente" DROP CONSTRAINT "RecetaIngrediente_empresaId_insumoProductoId_fkey";
ALTER TABLE "RecetaIngrediente" DROP CONSTRAINT "RecetaIngrediente_empresaId_unidadId_fkey";
ALTER TABLE "SustitutoRecetaIngrediente" DROP CONSTRAINT "SustitutoRecetaIngrediente_empresaId_fkey";
ALTER TABLE "SustitutoRecetaIngrediente" DROP CONSTRAINT "SustitutoRecetaIngrediente_empresaId_recetaIngredienteId_fkey";
ALTER TABLE "SustitutoRecetaIngrediente" DROP CONSTRAINT "SustitutoRecetaIngrediente_empresaId_insumoSustitutoId_fkey";
ALTER TABLE "RecetaPaso" DROP CONSTRAINT "RecetaPaso_empresaId_fkey";
ALTER TABLE "RecetaPaso" DROP CONSTRAINT "RecetaPaso_empresaId_recetaVersionId_fkey";
ALTER TABLE "RecetaPasoIngrediente" DROP CONSTRAINT "RecetaPasoIngrediente_empresaId_fkey";
ALTER TABLE "RecetaPasoIngrediente" DROP CONSTRAINT "RecetaPasoIngrediente_empresaId_recetaPasoId_fkey";
ALTER TABLE "RecetaPasoIngrediente" DROP CONSTRAINT "RecetaPasoIngrediente_empresaId_recetaIngredienteId_fkey";
ALTER TABLE "MotivoMerma" DROP CONSTRAINT "MotivoMerma_empresaId_fkey";
ALTER TABLE "DestinoConsumo" DROP CONSTRAINT "DestinoConsumo_empresaId_fkey";
ALTER TABLE "Seccion" DROP CONSTRAINT "Seccion_empresaId_fkey";
ALTER TABLE "Seccion" DROP CONSTRAINT "Seccion_empresaId_sucursalId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_sucursalId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_proveedorId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_clienteId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_promoCuentaId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_seccionDestinoId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_motivoId_fkey";
ALTER TABLE "Operacion" DROP CONSTRAINT "Operacion_empresaId_destinoId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_operacionId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_productoId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_seccionId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_conteoFisicoId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_traspasoSucursalId_fkey";
ALTER TABLE "MovimientoStock" DROP CONSTRAINT "MovimientoStock_empresaId_sustituyeAProductoId_fkey";
ALTER TABLE "ConteoFisico" DROP CONSTRAINT "ConteoFisico_empresaId_fkey";
ALTER TABLE "ConteoFisico" DROP CONSTRAINT "ConteoFisico_empresaId_sucursalId_fkey";
ALTER TABLE "ConteoFisico" DROP CONSTRAINT "ConteoFisico_empresaId_productoId_fkey";
ALTER TABLE "ConteoFisico" DROP CONSTRAINT "ConteoFisico_empresaId_seccionId_fkey";
ALTER TABLE "PrecioLocalProducto" DROP CONSTRAINT "PrecioLocalProducto_empresaId_fkey";
ALTER TABLE "PrecioLocalProducto" DROP CONSTRAINT "PrecioLocalProducto_empresaId_sucursalId_fkey";
ALTER TABLE "PrecioLocalProducto" DROP CONSTRAINT "PrecioLocalProducto_empresaId_productoId_fkey";
ALTER TABLE "RendimientoLocalIngrediente" DROP CONSTRAINT "RendimientoLocalIngrediente_empresaId_fkey";
ALTER TABLE "RendimientoLocalIngrediente" DROP CONSTRAINT "RendimientoLocalIngrediente_empresaId_recetaIngredienteId_fkey";
ALTER TABLE "RendimientoLocalIngrediente" DROP CONSTRAINT "RendimientoLocalIngrediente_empresaId_sucursalId_fkey";
ALTER TABLE "FrecuenciaConteoProducto" DROP CONSTRAINT "FrecuenciaConteoProducto_empresaId_fkey";
ALTER TABLE "FrecuenciaConteoProducto" DROP CONSTRAINT "FrecuenciaConteoProducto_empresaId_sucursalId_fkey";
ALTER TABLE "FrecuenciaConteoProducto" DROP CONSTRAINT "FrecuenciaConteoProducto_empresaId_productoId_fkey";
ALTER TABLE "StockMinimoProducto" DROP CONSTRAINT "StockMinimoProducto_empresaId_fkey";
ALTER TABLE "StockMinimoProducto" DROP CONSTRAINT "StockMinimoProducto_empresaId_sucursalId_fkey";
ALTER TABLE "StockMinimoProducto" DROP CONSTRAINT "StockMinimoProducto_empresaId_productoId_fkey";
ALTER TABLE "StockMinimoProducto" DROP CONSTRAINT "StockMinimoProducto_empresaId_seccionId_fkey";
ALTER TABLE "SeccionHabitualProducto" DROP CONSTRAINT "SeccionHabitualProducto_empresaId_fkey";
ALTER TABLE "SeccionHabitualProducto" DROP CONSTRAINT "SeccionHabitualProducto_empresaId_sucursalId_fkey";
ALTER TABLE "SeccionHabitualProducto" DROP CONSTRAINT "SeccionHabitualProducto_empresaId_productoId_fkey";
ALTER TABLE "SeccionHabitualProducto" DROP CONSTRAINT "SeccionHabitualProducto_empresaId_seccionId_fkey";
ALTER TABLE "PromocionProducto" DROP CONSTRAINT "PromocionProducto_empresaId_fkey";
ALTER TABLE "PromocionProducto" DROP CONSTRAINT "PromocionProducto_empresaId_sucursalId_fkey";
ALTER TABLE "PromocionProducto" DROP CONSTRAINT "PromocionProducto_empresaId_productoId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_origenSucursalId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_destinoSucursalId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_productoId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_seccionOrigenId_fkey";
ALTER TABLE "TraspasoSucursal" DROP CONSTRAINT "TraspasoSucursal_empresaId_seccionDestinoId_fkey";
ALTER TABLE "SeccionCarta" DROP CONSTRAINT "SeccionCarta_empresaId_fkey";
ALTER TABLE "ContenidoCartaProducto" DROP CONSTRAINT "ContenidoCartaProducto_empresaId_fkey";
ALTER TABLE "ContenidoCartaProducto" DROP CONSTRAINT "ContenidoCartaProducto_empresaId_productoId_fkey";
ALTER TABLE "ContenidoCartaProducto" DROP CONSTRAINT "ContenidoCartaProducto_empresaId_seccionCartaId_fkey";
ALTER TABLE "ContenidoCartaProducto" DROP CONSTRAINT "ContenidoCartaProducto_empresaId_generoCartaId_fkey";
ALTER TABLE "ItemAgrupadoCarta" DROP CONSTRAINT "ItemAgrupadoCarta_empresaId_fkey";
ALTER TABLE "ItemAgrupadoCarta" DROP CONSTRAINT "ItemAgrupadoCarta_empresaId_seccionCartaId_fkey";
ALTER TABLE "ItemAgrupadoCarta" DROP CONSTRAINT "ItemAgrupadoCarta_empresaId_generoCartaId_fkey";
ALTER TABLE "GeneroCarta" DROP CONSTRAINT "GeneroCarta_empresaId_fkey";
ALTER TABLE "OpcionItemAgrupadoCarta" DROP CONSTRAINT "OpcionItemAgrupadoCarta_empresaId_fkey";
ALTER TABLE "OpcionItemAgrupadoCarta" DROP CONSTRAINT "OpcionItemAgrupadoCarta_empresaId_itemAgrupadoCartaId_fkey";
ALTER TABLE "OpcionItemAgrupadoCarta" DROP CONSTRAINT "OpcionItemAgrupadoCarta_empresaId_productoId_fkey";
ALTER TABLE "PromoCarta" DROP CONSTRAINT "PromoCarta_empresaId_fkey";
ALTER TABLE "PromoCarta" DROP CONSTRAINT "PromoCarta_empresaId_sucursalId_fkey";
ALTER TABLE "PromoCarta" DROP CONSTRAINT "PromoCarta_empresaId_seccionCartaId_fkey";
ALTER TABLE "PromoCartaCupo" DROP CONSTRAINT "PromoCartaCupo_empresaId_fkey";
ALTER TABLE "PromoCartaCupo" DROP CONSTRAINT "PromoCartaCupo_empresaId_promoCartaId_fkey";
ALTER TABLE "PromoCartaCupo" DROP CONSTRAINT "PromoCartaCupo_empresaId_seccionCartaId_fkey";
ALTER TABLE "SucursalPublica" DROP CONSTRAINT "SucursalPublica_empresaId_fkey";
ALTER TABLE "SucursalPublica" DROP CONSTRAINT "SucursalPublica_empresaId_sucursalId_fkey";
ALTER TABLE "TemaCartaSucursal" DROP CONSTRAINT "TemaCartaSucursal_empresaId_fkey";
ALTER TABLE "TemaCartaSucursal" DROP CONSTRAINT "TemaCartaSucursal_empresaId_sucursalId_fkey";
ALTER TABLE "Mesa" DROP CONSTRAINT "Mesa_empresaId_fkey";
ALTER TABLE "Mesa" DROP CONSTRAINT "Mesa_empresaId_sucursalId_fkey";
ALTER TABLE "Cuenta" DROP CONSTRAINT "Cuenta_empresaId_fkey";
ALTER TABLE "Cuenta" DROP CONSTRAINT "Cuenta_empresaId_mesaId_fkey";
ALTER TABLE "Cuenta" DROP CONSTRAINT "Cuenta_empresaId_clienteId_fkey";
ALTER TABLE "PromoCuenta" DROP CONSTRAINT "PromoCuenta_empresaId_fkey";
ALTER TABLE "PromoCuenta" DROP CONSTRAINT "PromoCuenta_empresaId_cuentaId_fkey";
ALTER TABLE "PromoCuenta" DROP CONSTRAINT "PromoCuenta_empresaId_promoCartaId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_cuentaId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_productoId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_anulaAItemId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_operacionId_fkey";
ALTER TABLE "CuentaItem" DROP CONSTRAINT "CuentaItem_empresaId_promoCuentaId_fkey";
ALTER TABLE "EjemplarBoleta" DROP CONSTRAINT "EjemplarBoleta_empresaId_fkey";
ALTER TABLE "EjemplarBoleta" DROP CONSTRAINT "EjemplarBoleta_empresaId_sucursalId_fkey";
ALTER TABLE "EjemplarBoleta" DROP CONSTRAINT "EjemplarBoleta_empresaId_cuentaId_fkey";
ALTER TABLE "EjemplarBoleta" DROP CONSTRAINT "EjemplarBoleta_empresaId_corrigeAId_fkey";
ALTER TABLE "UsuarioEmpresa" DROP CONSTRAINT "UsuarioEmpresa_usuarioId_fkey";
ALTER TABLE "UsuarioEmpresa" DROP CONSTRAINT "UsuarioEmpresa_empresaId_fkey";
DROP INDEX "Sucursal_empresaId_nombre_key";
DROP INDEX "Sucursal_empresaId_id_key";
DROP INDEX "Rol_empresaId_nombre_key";
DROP INDEX "Rol_empresaId_id_key";
DROP INDEX "UsuarioSucursal_empresaId_id_key";
DROP INDEX "PermisoRol_empresaId_id_key";
DROP INDEX "CapacidadSucursal_empresaId_id_key";
DROP INDEX "RegistroAuditoria_empresaId_id_key";
DROP INDEX "Producto_empresaId_codigo_key";
DROP INDEX "Producto_empresaId_id_key";
DROP INDEX "DisponibilidadProducto_empresaId_id_key";
DROP INDEX "Insumo_empresaId_nombre_key";
DROP INDEX "Insumo_empresaId_id_key";
DROP INDEX "Grupo_empresaId_nombre_key";
DROP INDEX "Grupo_empresaId_id_key";
DROP INDEX "CategoriaProducto_empresaId_nombre_key";
DROP INDEX "CategoriaProducto_empresaId_id_key";
DROP INDEX "Unidad_empresaId_nombre_key";
DROP INDEX "Unidad_empresaId_id_key";
DROP INDEX "Presentacion_empresaId_id_key";
DROP INDEX "Proveedor_empresaId_codigo_key";
DROP INDEX "Proveedor_empresaId_nombre_key";
DROP INDEX "Proveedor_empresaId_id_key";
DROP INDEX "PagoConsignante_empresaId_id_key";
DROP INDEX "ProveedorPorProducto_empresaId_id_key";
DROP INDEX "Cliente_empresaId_nombre_key";
DROP INDEX "Cliente_empresaId_id_key";
DROP INDEX "RecetaVersion_empresaId_id_key";
DROP INDEX "RecetaIngrediente_empresaId_id_key";
DROP INDEX "SustitutoRecetaIngrediente_empresaId_id_key";
DROP INDEX "RecetaPaso_empresaId_id_key";
DROP INDEX "RecetaPasoIngrediente_empresaId_id_key";
DROP INDEX "MotivoMerma_empresaId_nombre_key";
DROP INDEX "MotivoMerma_empresaId_id_key";
DROP INDEX "DestinoConsumo_empresaId_nombre_key";
DROP INDEX "DestinoConsumo_empresaId_id_key";
DROP INDEX "Seccion_empresaId_id_key";
DROP INDEX "Operacion_empresaId_id_key";
DROP INDEX "MovimientoStock_empresaId_id_key";
DROP INDEX "ConteoFisico_empresaId_id_key";
DROP INDEX "PrecioLocalProducto_empresaId_id_key";
DROP INDEX "RendimientoLocalIngrediente_empresaId_id_key";
DROP INDEX "FrecuenciaConteoProducto_empresaId_id_key";
DROP INDEX "StockMinimoProducto_empresaId_id_key";
DROP INDEX "SeccionHabitualProducto_empresaId_id_key";
DROP INDEX "PromocionProducto_empresaId_id_key";
DROP INDEX "TraspasoSucursal_empresaId_id_key";
DROP INDEX "SeccionCarta_empresaId_nombre_key";
DROP INDEX "SeccionCarta_empresaId_id_key";
DROP INDEX "ContenidoCartaProducto_empresaId_productoId_key";
DROP INDEX "ContenidoCartaProducto_empresaId_id_key";
DROP INDEX "ItemAgrupadoCarta_empresaId_nombre_key";
DROP INDEX "ItemAgrupadoCarta_empresaId_id_key";
DROP INDEX "GeneroCarta_empresaId_nombre_key";
DROP INDEX "GeneroCarta_empresaId_id_key";
DROP INDEX "OpcionItemAgrupadoCarta_empresaId_productoId_key";
DROP INDEX "OpcionItemAgrupadoCarta_empresaId_id_key";
DROP INDEX "PromoCarta_empresaId_id_key";
DROP INDEX "PromoCartaCupo_empresaId_id_key";
DROP INDEX "SucursalPublica_empresaId_sucursalId_key";
DROP INDEX "SucursalPublica_empresaId_slug_key";
DROP INDEX "SucursalPublica_empresaId_id_key";
DROP INDEX "TemaCartaSucursal_empresaId_sucursalId_key";
DROP INDEX "TemaCartaSucursal_empresaId_id_key";
DROP INDEX "Mesa_empresaId_id_key";
DROP INDEX "Cuenta_empresaId_id_key";
DROP INDEX "PromoCuenta_empresaId_id_key";
DROP INDEX "CuentaItem_empresaId_id_key";
DROP INDEX "EjemplarBoleta_empresaId_id_key";
DROP INDEX "CapacidadSucursal_accionClave_default_key";
DROP INDEX "Producto_nombre_lower_key";
DROP INDEX "Proveedor_nombre_lower_key";
DROP INDEX "Insumo_nombre_lower_key";
DROP INDEX "CategoriaProducto_nombre_lower_key";
DROP INDEX "Unidad_nombre_lower_key";
DROP INDEX "Grupo_nombre_lower_key";

-- 2) Se quitan las columnas empresaId y las tablas de plataforma.
ALTER TABLE "Sucursal" DROP COLUMN "empresaId";
ALTER TABLE "Rol" DROP COLUMN "empresaId";
ALTER TABLE "UsuarioSucursal" DROP COLUMN "empresaId";
ALTER TABLE "PermisoRol" DROP COLUMN "empresaId";
ALTER TABLE "CapacidadSucursal" DROP COLUMN "empresaId";
ALTER TABLE "RegistroAuditoria" DROP COLUMN "empresaId";
ALTER TABLE "Producto" DROP COLUMN "empresaId";
ALTER TABLE "DisponibilidadProducto" DROP COLUMN "empresaId";
ALTER TABLE "Insumo" DROP COLUMN "empresaId";
ALTER TABLE "Grupo" DROP COLUMN "empresaId";
ALTER TABLE "CategoriaProducto" DROP COLUMN "empresaId";
ALTER TABLE "Unidad" DROP COLUMN "empresaId";
ALTER TABLE "Presentacion" DROP COLUMN "empresaId";
ALTER TABLE "Proveedor" DROP COLUMN "empresaId";
ALTER TABLE "PagoConsignante" DROP COLUMN "empresaId";
ALTER TABLE "ProveedorPorProducto" DROP COLUMN "empresaId";
ALTER TABLE "Cliente" DROP COLUMN "empresaId";
ALTER TABLE "RecetaVersion" DROP COLUMN "empresaId";
ALTER TABLE "RecetaIngrediente" DROP COLUMN "empresaId";
ALTER TABLE "SustitutoRecetaIngrediente" DROP COLUMN "empresaId";
ALTER TABLE "RecetaPaso" DROP COLUMN "empresaId";
ALTER TABLE "RecetaPasoIngrediente" DROP COLUMN "empresaId";
ALTER TABLE "MotivoMerma" DROP COLUMN "empresaId";
ALTER TABLE "DestinoConsumo" DROP COLUMN "empresaId";
ALTER TABLE "Seccion" DROP COLUMN "empresaId";
ALTER TABLE "Operacion" DROP COLUMN "empresaId";
ALTER TABLE "MovimientoStock" DROP COLUMN "empresaId";
ALTER TABLE "ConteoFisico" DROP COLUMN "empresaId";
ALTER TABLE "PrecioLocalProducto" DROP COLUMN "empresaId";
ALTER TABLE "RendimientoLocalIngrediente" DROP COLUMN "empresaId";
ALTER TABLE "FrecuenciaConteoProducto" DROP COLUMN "empresaId";
ALTER TABLE "StockMinimoProducto" DROP COLUMN "empresaId";
ALTER TABLE "SeccionHabitualProducto" DROP COLUMN "empresaId";
ALTER TABLE "PromocionProducto" DROP COLUMN "empresaId";
ALTER TABLE "TraspasoSucursal" DROP COLUMN "empresaId";
ALTER TABLE "SeccionCarta" DROP COLUMN "empresaId";
ALTER TABLE "ContenidoCartaProducto" DROP COLUMN "empresaId";
ALTER TABLE "ItemAgrupadoCarta" DROP COLUMN "empresaId";
ALTER TABLE "GeneroCarta" DROP COLUMN "empresaId";
ALTER TABLE "OpcionItemAgrupadoCarta" DROP COLUMN "empresaId";
ALTER TABLE "PromoCarta" DROP COLUMN "empresaId";
ALTER TABLE "PromoCartaCupo" DROP COLUMN "empresaId";
ALTER TABLE "SucursalPublica" DROP COLUMN "empresaId";
ALTER TABLE "TemaCartaSucursal" DROP COLUMN "empresaId";
ALTER TABLE "Mesa" DROP COLUMN "empresaId";
ALTER TABLE "Cuenta" DROP COLUMN "empresaId";
ALTER TABLE "PromoCuenta" DROP COLUMN "empresaId";
ALTER TABLE "CuentaItem" DROP COLUMN "empresaId";
ALTER TABLE "EjemplarBoleta" DROP COLUMN "empresaId";
DROP TABLE "Empresa";
DROP TABLE "UsuarioEmpresa";
DROP TYPE "EstadoEmpresa";
DROP FUNCTION app_empresa_actual();

-- 3) Se restauran unicidades globales, índices manuales y FK simples.
CREATE UNIQUE INDEX "Sucursal_nombre_key" ON "Sucursal"("nombre");
CREATE UNIQUE INDEX "Rol_nombre_key" ON "Rol"("nombre");
CREATE UNIQUE INDEX "Producto_codigo_key" ON "Producto"("codigo");
CREATE UNIQUE INDEX "Insumo_nombre_key" ON "Insumo"("nombre");
CREATE UNIQUE INDEX "Grupo_nombre_key" ON "Grupo"("nombre");
CREATE UNIQUE INDEX "CategoriaProducto_nombre_key" ON "CategoriaProducto"("nombre");
CREATE UNIQUE INDEX "Unidad_nombre_key" ON "Unidad"("nombre");
CREATE UNIQUE INDEX "Proveedor_codigo_key" ON "Proveedor"("codigo");
CREATE UNIQUE INDEX "Proveedor_nombre_key" ON "Proveedor"("nombre");
CREATE UNIQUE INDEX "Cliente_nombre_key" ON "Cliente"("nombre");
CREATE UNIQUE INDEX "MotivoMerma_nombre_key" ON "MotivoMerma"("nombre");
CREATE UNIQUE INDEX "DestinoConsumo_nombre_key" ON "DestinoConsumo"("nombre");
CREATE UNIQUE INDEX "SeccionCarta_nombre_key" ON "SeccionCarta"("nombre");
CREATE UNIQUE INDEX "ContenidoCartaProducto_productoId_key" ON "ContenidoCartaProducto"("productoId");
CREATE UNIQUE INDEX "ItemAgrupadoCarta_nombre_key" ON "ItemAgrupadoCarta"("nombre");
CREATE UNIQUE INDEX "GeneroCarta_nombre_key" ON "GeneroCarta"("nombre");
CREATE UNIQUE INDEX "OpcionItemAgrupadoCarta_productoId_key" ON "OpcionItemAgrupadoCarta"("productoId");
CREATE UNIQUE INDEX "SucursalPublica_sucursalId_key" ON "SucursalPublica"("sucursalId");
CREATE UNIQUE INDEX "SucursalPublica_slug_key" ON "SucursalPublica"("slug");
CREATE UNIQUE INDEX "TemaCartaSucursal_sucursalId_key" ON "TemaCartaSucursal"("sucursalId");
ALTER TABLE "UsuarioSucursal" ADD CONSTRAINT "UsuarioSucursal_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "UsuarioSucursal" ADD CONSTRAINT "UsuarioSucursal_rolId_fkey" FOREIGN KEY ("rolId") REFERENCES "Rol"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PermisoRol" ADD CONSTRAINT "PermisoRol_rolId_fkey" FOREIGN KEY ("rolId") REFERENCES "Rol"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CapacidadSucursal" ADD CONSTRAINT "CapacidadSucursal_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RegistroAuditoria" ADD CONSTRAINT "RegistroAuditoria_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Producto" ADD CONSTRAINT "Producto_categoriaId_fkey" FOREIGN KEY ("categoriaId") REFERENCES "CategoriaProducto"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Producto" ADD CONSTRAINT "Producto_unidadCompraId_fkey" FOREIGN KEY ("unidadCompraId") REFERENCES "Unidad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Producto" ADD CONSTRAINT "Producto_unidadStockId_fkey" FOREIGN KEY ("unidadStockId") REFERENCES "Unidad"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Producto" ADD CONSTRAINT "Producto_insumoId_fkey" FOREIGN KEY ("insumoId") REFERENCES "Insumo"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Producto" ADD CONSTRAINT "Producto_proveedorConsignacionId_fkey" FOREIGN KEY ("proveedorConsignacionId") REFERENCES "Proveedor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DisponibilidadProducto" ADD CONSTRAINT "DisponibilidadProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DisponibilidadProducto" ADD CONSTRAINT "DisponibilidadProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Insumo" ADD CONSTRAINT "Insumo_grupoId_fkey" FOREIGN KEY ("grupoId") REFERENCES "Grupo"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Grupo" ADD CONSTRAINT "Grupo_grupoPadreId_fkey" FOREIGN KEY ("grupoPadreId") REFERENCES "Grupo"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Presentacion" ADD CONSTRAINT "Presentacion_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Presentacion" ADD CONSTRAINT "Presentacion_unidadCompraId_fkey" FOREIGN KEY ("unidadCompraId") REFERENCES "Unidad"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PagoConsignante" ADD CONSTRAINT "PagoConsignante_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PagoConsignante" ADD CONSTRAINT "PagoConsignante_proveedorId_fkey" FOREIGN KEY ("proveedorId") REFERENCES "Proveedor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProveedorPorProducto" ADD CONSTRAINT "ProveedorPorProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProveedorPorProducto" ADD CONSTRAINT "ProveedorPorProducto_proveedorId_fkey" FOREIGN KEY ("proveedorId") REFERENCES "Proveedor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ProveedorPorProducto" ADD CONSTRAINT "ProveedorPorProducto_unidadCompraId_fkey" FOREIGN KEY ("unidadCompraId") REFERENCES "Unidad"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecetaVersion" ADD CONSTRAINT "RecetaVersion_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecetaVersion" ADD CONSTRAINT "RecetaVersion_rendimientoUnidadId_fkey" FOREIGN KEY ("rendimientoUnidadId") REFERENCES "Unidad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecetaVersion" ADD CONSTRAINT "RecetaVersion_racionUnidadId_fkey" FOREIGN KEY ("racionUnidadId") REFERENCES "Unidad"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RecetaIngrediente" ADD CONSTRAINT "RecetaIngrediente_recetaVersionId_fkey" FOREIGN KEY ("recetaVersionId") REFERENCES "RecetaVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecetaIngrediente" ADD CONSTRAINT "RecetaIngrediente_insumoProductoId_fkey" FOREIGN KEY ("insumoProductoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecetaIngrediente" ADD CONSTRAINT "RecetaIngrediente_unidadId_fkey" FOREIGN KEY ("unidadId") REFERENCES "Unidad"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SustitutoRecetaIngrediente" ADD CONSTRAINT "SustitutoRecetaIngrediente_recetaIngredienteId_fkey" FOREIGN KEY ("recetaIngredienteId") REFERENCES "RecetaIngrediente"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SustitutoRecetaIngrediente" ADD CONSTRAINT "SustitutoRecetaIngrediente_insumoSustitutoId_fkey" FOREIGN KEY ("insumoSustitutoId") REFERENCES "Insumo"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RecetaPaso" ADD CONSTRAINT "RecetaPaso_recetaVersionId_fkey" FOREIGN KEY ("recetaVersionId") REFERENCES "RecetaVersion"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecetaPasoIngrediente" ADD CONSTRAINT "RecetaPasoIngrediente_recetaPasoId_fkey" FOREIGN KEY ("recetaPasoId") REFERENCES "RecetaPaso"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecetaPasoIngrediente" ADD CONSTRAINT "RecetaPasoIngrediente_recetaIngredienteId_fkey" FOREIGN KEY ("recetaIngredienteId") REFERENCES "RecetaIngrediente"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Seccion" ADD CONSTRAINT "Seccion_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_proveedorId_fkey" FOREIGN KEY ("proveedorId") REFERENCES "Proveedor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "Cliente"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_promoCuentaId_fkey" FOREIGN KEY ("promoCuentaId") REFERENCES "PromoCuenta"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_seccionDestinoId_fkey" FOREIGN KEY ("seccionDestinoId") REFERENCES "Seccion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_motivoId_fkey" FOREIGN KEY ("motivoId") REFERENCES "MotivoMerma"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Operacion" ADD CONSTRAINT "Operacion_destinoId_fkey" FOREIGN KEY ("destinoId") REFERENCES "DestinoConsumo"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_operacionId_fkey" FOREIGN KEY ("operacionId") REFERENCES "Operacion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_seccionId_fkey" FOREIGN KEY ("seccionId") REFERENCES "Seccion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_conteoFisicoId_fkey" FOREIGN KEY ("conteoFisicoId") REFERENCES "ConteoFisico"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_traspasoSucursalId_fkey" FOREIGN KEY ("traspasoSucursalId") REFERENCES "TraspasoSucursal"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MovimientoStock" ADD CONSTRAINT "MovimientoStock_sustituyeAProductoId_fkey" FOREIGN KEY ("sustituyeAProductoId") REFERENCES "Producto"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ConteoFisico" ADD CONSTRAINT "ConteoFisico_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ConteoFisico" ADD CONSTRAINT "ConteoFisico_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ConteoFisico" ADD CONSTRAINT "ConteoFisico_seccionId_fkey" FOREIGN KEY ("seccionId") REFERENCES "Seccion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PrecioLocalProducto" ADD CONSTRAINT "PrecioLocalProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PrecioLocalProducto" ADD CONSTRAINT "PrecioLocalProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RendimientoLocalIngrediente" ADD CONSTRAINT "RendimientoLocalIngrediente_recetaIngredienteId_fkey" FOREIGN KEY ("recetaIngredienteId") REFERENCES "RecetaIngrediente"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RendimientoLocalIngrediente" ADD CONSTRAINT "RendimientoLocalIngrediente_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FrecuenciaConteoProducto" ADD CONSTRAINT "FrecuenciaConteoProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FrecuenciaConteoProducto" ADD CONSTRAINT "FrecuenciaConteoProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMinimoProducto" ADD CONSTRAINT "StockMinimoProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMinimoProducto" ADD CONSTRAINT "StockMinimoProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMinimoProducto" ADD CONSTRAINT "StockMinimoProducto_seccionId_fkey" FOREIGN KEY ("seccionId") REFERENCES "Seccion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SeccionHabitualProducto" ADD CONSTRAINT "SeccionHabitualProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SeccionHabitualProducto" ADD CONSTRAINT "SeccionHabitualProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SeccionHabitualProducto" ADD CONSTRAINT "SeccionHabitualProducto_seccionId_fkey" FOREIGN KEY ("seccionId") REFERENCES "Seccion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromocionProducto" ADD CONSTRAINT "PromocionProducto_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromocionProducto" ADD CONSTRAINT "PromocionProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TraspasoSucursal" ADD CONSTRAINT "TraspasoSucursal_origenSucursalId_fkey" FOREIGN KEY ("origenSucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TraspasoSucursal" ADD CONSTRAINT "TraspasoSucursal_destinoSucursalId_fkey" FOREIGN KEY ("destinoSucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TraspasoSucursal" ADD CONSTRAINT "TraspasoSucursal_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TraspasoSucursal" ADD CONSTRAINT "TraspasoSucursal_seccionOrigenId_fkey" FOREIGN KEY ("seccionOrigenId") REFERENCES "Seccion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TraspasoSucursal" ADD CONSTRAINT "TraspasoSucursal_seccionDestinoId_fkey" FOREIGN KEY ("seccionDestinoId") REFERENCES "Seccion"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ContenidoCartaProducto" ADD CONSTRAINT "ContenidoCartaProducto_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ContenidoCartaProducto" ADD CONSTRAINT "ContenidoCartaProducto_seccionCartaId_fkey" FOREIGN KEY ("seccionCartaId") REFERENCES "SeccionCarta"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ContenidoCartaProducto" ADD CONSTRAINT "ContenidoCartaProducto_generoCartaId_fkey" FOREIGN KEY ("generoCartaId") REFERENCES "GeneroCarta"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ItemAgrupadoCarta" ADD CONSTRAINT "ItemAgrupadoCarta_seccionCartaId_fkey" FOREIGN KEY ("seccionCartaId") REFERENCES "SeccionCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ItemAgrupadoCarta" ADD CONSTRAINT "ItemAgrupadoCarta_generoCartaId_fkey" FOREIGN KEY ("generoCartaId") REFERENCES "GeneroCarta"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OpcionItemAgrupadoCarta" ADD CONSTRAINT "OpcionItemAgrupadoCarta_itemAgrupadoCartaId_fkey" FOREIGN KEY ("itemAgrupadoCartaId") REFERENCES "ItemAgrupadoCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OpcionItemAgrupadoCarta" ADD CONSTRAINT "OpcionItemAgrupadoCarta_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromoCarta" ADD CONSTRAINT "PromoCarta_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromoCarta" ADD CONSTRAINT "PromoCarta_seccionCartaId_fkey" FOREIGN KEY ("seccionCartaId") REFERENCES "SeccionCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromoCartaCupo" ADD CONSTRAINT "PromoCartaCupo_promoCartaId_fkey" FOREIGN KEY ("promoCartaId") REFERENCES "PromoCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromoCartaCupo" ADD CONSTRAINT "PromoCartaCupo_seccionCartaId_fkey" FOREIGN KEY ("seccionCartaId") REFERENCES "SeccionCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SucursalPublica" ADD CONSTRAINT "SucursalPublica_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TemaCartaSucursal" ADD CONSTRAINT "TemaCartaSucursal_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Mesa" ADD CONSTRAINT "Mesa_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Cuenta" ADD CONSTRAINT "Cuenta_mesaId_fkey" FOREIGN KEY ("mesaId") REFERENCES "Mesa"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Cuenta" ADD CONSTRAINT "Cuenta_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "Cliente"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PromoCuenta" ADD CONSTRAINT "PromoCuenta_cuentaId_fkey" FOREIGN KEY ("cuentaId") REFERENCES "Cuenta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PromoCuenta" ADD CONSTRAINT "PromoCuenta_promoCartaId_fkey" FOREIGN KEY ("promoCartaId") REFERENCES "PromoCarta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CuentaItem" ADD CONSTRAINT "CuentaItem_cuentaId_fkey" FOREIGN KEY ("cuentaId") REFERENCES "Cuenta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CuentaItem" ADD CONSTRAINT "CuentaItem_productoId_fkey" FOREIGN KEY ("productoId") REFERENCES "Producto"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CuentaItem" ADD CONSTRAINT "CuentaItem_anulaAItemId_fkey" FOREIGN KEY ("anulaAItemId") REFERENCES "CuentaItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CuentaItem" ADD CONSTRAINT "CuentaItem_operacionId_fkey" FOREIGN KEY ("operacionId") REFERENCES "Operacion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CuentaItem" ADD CONSTRAINT "CuentaItem_promoCuentaId_fkey" FOREIGN KEY ("promoCuentaId") REFERENCES "PromoCuenta"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "EjemplarBoleta" ADD CONSTRAINT "EjemplarBoleta_sucursalId_fkey" FOREIGN KEY ("sucursalId") REFERENCES "Sucursal"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EjemplarBoleta" ADD CONSTRAINT "EjemplarBoleta_cuentaId_fkey" FOREIGN KEY ("cuentaId") REFERENCES "Cuenta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EjemplarBoleta" ADD CONSTRAINT "EjemplarBoleta_corrigeAId_fkey" FOREIGN KEY ("corrigeAId") REFERENCES "EjemplarBoleta"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE UNIQUE INDEX "Producto_nombre_lower_key" ON "Producto" (lower("nombre"));
CREATE UNIQUE INDEX "Proveedor_nombre_lower_key" ON "Proveedor" (lower("nombre"));
CREATE UNIQUE INDEX "Insumo_nombre_lower_key" ON "Insumo" (lower("nombre"));
CREATE UNIQUE INDEX "CategoriaProducto_nombre_lower_key" ON "CategoriaProducto" (lower("nombre"));
CREATE UNIQUE INDEX "Unidad_nombre_lower_key" ON "Unidad" (lower("nombre"));
CREATE UNIQUE INDEX "Grupo_nombre_lower_key" ON "Grupo" (lower("nombre"));
CREATE UNIQUE INDEX "CapacidadSucursal_accionClave_default_key" ON "CapacidadSucursal" ("accionClave") WHERE "sucursalId" IS NULL;
